backend:
  name: github
  repo: aeenak/website
  branch: main

media_folder: "Images/uploads"
public_folder: "/Images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/home.json"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "text" }
          - { label: "CTA Text", name: "cta", widget: "string" }
